apiVersion: v1
kind: Template
metadata:
  name: spring-boot-istio-ab-tests-booster-client-service-consumer
  annotations:
    iconClass: icon-spring
    tags: spring-boot, circuit breaker, java, microservice
    openshift.io/display-name: Spring Boot - Istio Distributed Tracing
    openshift.io/provider-display-name: "Red Hat, Inc."
    description: >-
      The A/B Testing Istio booster - suggestion service
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: ARTIFACT_COPY_ARGS
  description: Syntax to be used to copy uberjar files to the target directory
  displayName: Copy Args
  value: '*-exec.jar'
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
- name: MAVEN_MIRROR_URL
  description: Maven Nexus Repository to be used during build phase
  displayName:
  required: false
objects:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: client-service-consumer
    annotations:
      kubernetes.io/ingress.class: istio
  spec:
    rules:
    - http:
        paths:
        - path: /example
          backend:
            serviceName: client-service-consumer
            servicePort: 8080
        - path: /example/.*
          backend:
            serviceName: client-service-consumer
            servicePort: 8080
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: client-service-consumer
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime-client-consumer
  spec:
    tags:
    - name: "1.3-5"
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.3-5
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: client-service-consumer
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: client-service-consumer:1.5.12-2
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime-client-consumer:1.3-5
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
        - name: MAVEN_MIRROR_URL
          value: "${MAVEN_MIRROR_URL}"
        - name: ARTIFACT_COPY_ARGS
          value: "${ARTIFACT_COPY_ARGS}"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: client-service-consumer
      provider: snowdrop
      version: "1.5.12-2"
      group: io.openshift.booster
    name: client-service-consumer
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: client-service-consumer
      provider: snowdrop
      group: io.openshift.booster
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: client-service-consumer
      provider: snowdrop
      version: "1.5.12-2"
      group: io.openshift.booster
    name: client-service-consumer
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: client-service-consumer
      provider: snowdrop
      group: io.openshift.booster
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: 'true'
        labels:
          app: client-service-consumer
          provider: snowdrop
          version: "1.5.12-2"
          group: io.openshift.booster
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: client-service-consumer:1.5.12-2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: client-service-consumer:1.5.12-2
      type: ImageChange
